name: Puppeteer and Lighthouse

on:
  workflow_dispatch:  # This makes the workflow manually triggerable from the GitHub UI

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 3: Run the scripts
      - name: Run the scripts
        run: node scripts/main.mjs

      # Step 4: Archive the artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: script-artifacts
          path: auto_*  # Ensure the path matches where the artifacts are stored
